version: '3.3'

networks:
  rotten_net:
    driver: bridge

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    networks:
      - rotten_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
  rotten-potatoes:
    image: giancarloh/rotten-potatoes:v1
    depends_on:
      - mongodb
    networks:
      - rotten_net
    ports:
      - 5000:5000
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongodb
      MONGODB_PORT: "27017"
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd
